name: Run fetch_all_teams

permissions:
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run fetch_all_teams.py
        run: python fetch_all_teams.py
        env:
          GITHUB_TOKEN: ${{ secrets.VOLLEYBALLDATABASED }}
          
